#!/bin/bash
# Receptura pakietu dla wpkg

pkgname=fontconfig
pkgver=2.15.0
pkgrel=1
pkgdesc="Konfiguracja czcionek"
arch=x86_64
url="https://www.freedesktop.org/wiki/Software/fontconfig/"
depends=(freetype)
source="https://www.freedesktop.org/software/fontconfig/release/fontconfig-${pkgver}.tar.xz"
sha256sum="SKIP"

build() {
    cd "${pkgname}-${pkgver}"
    ./configure --prefix=/usr CC=musl-gcc
    make -j$(nproc)
}

package() {
    cd "${pkgname}-${pkgver}"
    make DESTDIR="${PKGDIR}" install
}
