#!/bin/bash
# Receptura pakietu dla wpkg

pkgname=vis
pkgver=0.9
pkgrel=1
pkgdesc="Edytor tekstu inspirowany vi/vim"
arch=x86_64
url="https://github.com/martanne/vis"
depends=(ncurses)
source="https://github.com/martanne/vis/releases/download/v${pkgver}/vis-${pkgver}.tar.gz"
sha256sum="SKIP"

build() {
    cd "${pkgname}-${pkgver}"
    ./configure --prefix=/usr CC=musl-gcc
    make -j$(nproc)
}

package() {
    cd "${pkgname}-${pkgver}"
    make DESTDIR="${PKGDIR}" install
}
